{% set name = "pytest-bdd" %}
{% set version = "8.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pytest-dev/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 92162b4b92eea7092e07e978b42e552543fe66e4253534567825883cbaf9077b

build:
  number: 0
  skip: true  # [py<39]
  entry_points:
    - pytest-bdd = pytest_bdd.scripts:main
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - poetry-core >=1.0.0
  run:
    - python
    - mako
    - parse
    - parse_type
    - pytest >=7.0.0
    - typing-extensions
    - packaging
    - gherkin-official >=29.0.0,<30.0.0

# These tests generally have problems with paths on Windows
#E AssertionError: assert 'migrated: C:...\\__init__.py' == 'migrated: C:...s/__init__.py'
#E assert 'C:\\does\\not\\exist\\steps.feature' in "[Errno 2] No such file or directory: 'C:\\\\does\\\\not\\\\exist\\\\steps.feature'"
{% set ignore_test = [
  "test_feature_path_not_found",
  "test_feature_path_by_param_not_found",
  "test_generate",
  "test_migrate",
]%}

test:
  source_files:
    - tests
    - src
    - pyproject.toml
    - pytest.ini
  imports:
    - pytest_bdd
  requires:
    - pip
  commands:
    - pip check
    - pytest-bdd --help
    - pytest -v tests -k "not ({{ ignore_test | join(" or ") }})" # [win]
    - pytest -v tests # [not win]

about:
  home: https://github.com/pytest-dev/pytest-bdd
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: BDD for pytest
  description: pytest-bdd implements a subset of the Gherkin language to enable automating project requirements testing and to facilitate behavioral driven development.
  dev_url: https://github.com/pytest-dev/pytest-bdd
  doc_url: https://pytest-bdd.readthedocs.io

extra:
  recipe-maintainers:
    - m0nonoke
    - PertuyF
    - breathe
  skip-lints:
    - missing_wheel