{% set name = "pytest-bdd" %}
{% set version = "7.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: cb11e33b4419bd281cd6f74027c0b1eedeaf8f8d187edc897b4a61ae976ef9f1

build:
  number: 0
  skip: true  # [py<38]
  entry_points:
    - pytest-bdd = pytest_bdd.scripts:main
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - poetry-core >=1.0.0
  run:
    - python
    - mako
    - parse
    - parse_type
    - pytest >=6.2.0
    - typing-extensions

test:
  imports:
    - pytest_bdd
  requires:
    - pip
  commands:
    - pip check
    - pytest-bdd --help

about:
  home: https://github.com/pytest-dev/pytest-bdd
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: BDD for pytest
  description: pytest-bdd implements a subset of the Gherkin language to enable automating project requirements testing and to facilitate behavioral driven development.
  dev_url: https://github.com/pytest-dev/pytest-bdd
  doc_url: https://pytest-bdd.readthedocs.io

extra:
  recipe-maintainers:
    - m0nonoke
    - PertuyF
    - breathe
  skip-lints:
    - missing_wheel