travis:
  secure:
    BINSTAR_TOKEN: nBmiDcr1oaojynNB7Pgufc3l+EUCN8UuAcTZhZqxd9MHTrmPAKjEpseq7BUoyFw1l40SrGL7CAJmaGsXM7UBRJTUBs3qOFG/JzOl7FiQgbqCvgk/RuAtz/bNo7zXk2mBXQHkqK8YaENDHTi4XN75OOlxeN7WHXM0e/5kb8Tg+FSE0D87eChw4Qz9lsN/m22Fd7H4voVjwgX6j/eEAUpfmhTW8JNoqAnkGXm8wdSEIZbT/Wl2EsQLwnnBheRuVKXBM94/M/MdyfNC5yGKMQFsCiCDHBZrBlCElCBueTaYG/B88Zs+98FalXRB7KRAfN0/z+Ea9XPRT29Snv3CgkzXVRohAoi2BQ4puqDsVsURI0n4/Us7osSoVDy9rrZcouCvLu3uMwRQ+9D5mbd8lzGQBkXv2HuHerrJ6jCE0Tm3KvwPcBjLhJx+estGYYViz5WOn3UynR6/1QMIWrd8IicUfRKu3we3loO+Fb3Se42XlwL9UlJTZZkesNuxdIWRuHIMYK4ywl+1X2giIx8204qBVqLcgbJgHaou+6Svczk77n4+YFMlAVbvAdxO3w/ya5GfNFVphOiYenSVZbB2EfHr2Xzi2/Awjhw09u1RZQGAxqMc1ERSVI4w9jWgbu7oyFsp4Wq5Av8ldWDVoSkQjmuhSJNQdEAd99JuhQsmG3dVlKI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
